#ifndef _RENDER_TEXTURE_H
#define _RENDER_TEXTURE_H
#include "Texture.h"

#include <unordered_map>
enum class BufferAttachment
{
    ColorAttachment0 = GL_COLOR_ATTACHMENT0,
    ColorAttachment1 = GL_COLOR_ATTACHMENT1,
    ColorAttachment2 = GL_COLOR_ATTACHMENT2,
    ColorAttachment3 = GL_COLOR_ATTACHMENT3,
    ColorAttachment4 = GL_COLOR_ATTACHMENT4,
    ColorAttachment5 = GL_COLOR_ATTACHMENT5,
    ColorAttachment6 = GL_COLOR_ATTACHMENT6,
    ColorAttachment7 = GL_COLOR_ATTACHMENT7,
    ColorAttachment8 = GL_COLOR_ATTACHMENT8,
    ColorAttachment9 = GL_COLOR_ATTACHMENT9,
    ColorAttachment10 = GL_COLOR_ATTACHMENT10,
    ColorAttachment11 = GL_COLOR_ATTACHMENT11,
    ColorAttachment12 = GL_COLOR_ATTACHMENT12,
    ColorAttachment13 = GL_COLOR_ATTACHMENT13,
    ColorAttachment14 = GL_COLOR_ATTACHMENT14,
    ColorAttachment15 = GL_COLOR_ATTACHMENT15,
    ColorAttachment16 = GL_COLOR_ATTACHMENT16,
    ColorAttachment17 = GL_COLOR_ATTACHMENT17,
    ColorAttachment18 = GL_COLOR_ATTACHMENT18,
    ColorAttachment19 = GL_COLOR_ATTACHMENT19,
    ColorAttachment20 = GL_COLOR_ATTACHMENT20,
    ColorAttachment21 = GL_COLOR_ATTACHMENT21,
    ColorAttachment22 = GL_COLOR_ATTACHMENT22,
    ColorAttachment23 = GL_COLOR_ATTACHMENT23,
    ColorAttachment24 = GL_COLOR_ATTACHMENT24,
    ColorAttachment25 = GL_COLOR_ATTACHMENT25,
    ColorAttachment26 = GL_COLOR_ATTACHMENT26,
    ColorAttachment27 = GL_COLOR_ATTACHMENT27,
    ColorAttachment28 = GL_COLOR_ATTACHMENT28,
    ColorAttachment29 = GL_COLOR_ATTACHMENT29,
    ColorAttachment30 = GL_COLOR_ATTACHMENT30,
    ColorAttachment31 = GL_COLOR_ATTACHMENT31,
    DepthAttachment = GL_DEPTH_ATTACHMENT,
    StencilAttachment = GL_STENCIL_ATTACHMENT,
    Depth_Stencil_Attachment = GL_DEPTH_STENCIL_ATTACHMENT,
};


enum class BlitBitField
{
    COLOR_BIT = GL_COLOR_BUFFER_BIT,
    DEPTH_BIT = GL_DEPTH_BUFFER_BIT,
    STENCIL_BIT = GL_STENCIL_BUFFER_BIT,
};

enum class BlitFilter
{
    NEAREST = GL_NEAREST,
    LINEAR = GL_LINEAR,
};

enum class DrawBufferType
{
    NONE = GL_NONE,
    FRONT_LEFT = GL_FRONT_LEFT,
    FRONT_RIGHT = GL_FRONT_RIGHT,
    BACK_LEFT = GL_BACK_LEFT,
    BACK_RIGHT = GL_BACK_RIGHT,
    FRONT = GL_FRONT,
    BACK = GL_BACK,
    LEFT = GL_LEFT,
    RIGHT = GL_RIGHT,
    FRONT_AND_BACK = GL_FRONT_AND_BACK,
    COLOR_ATTACHMENT0 = GL_COLOR_ATTACHMENT0,
    COLOR_ATTACHMENT1 = GL_COLOR_ATTACHMENT1,
    COLOR_ATTACHMENT2 = GL_COLOR_ATTACHMENT2,
    COLOR_ATTACHMENT3 = GL_COLOR_ATTACHMENT3,
    COLOR_ATTACHMENT4 = GL_COLOR_ATTACHMENT4,
    COLOR_ATTACHMENT5 = GL_COLOR_ATTACHMENT5,
    COLOR_ATTACHMENT6 = GL_COLOR_ATTACHMENT6,
    COLOR_ATTACHMENT7 = GL_COLOR_ATTACHMENT7,
    COLOR_ATTACHMENT8 = GL_COLOR_ATTACHMENT8,
    COLOR_ATTACHMENT9 = GL_COLOR_ATTACHMENT9,
    COLOR_ATTACHMENT10 = GL_COLOR_ATTACHMENT10,
    COLOR_ATTACHMENT11 = GL_COLOR_ATTACHMENT11,
    COLOR_ATTACHMENT12 = GL_COLOR_ATTACHMENT12,
    COLOR_ATTACHMENT13 = GL_COLOR_ATTACHMENT13,
    COLOR_ATTACHMENT14 = GL_COLOR_ATTACHMENT14,
    COLOR_ATTACHMENT15 = GL_COLOR_ATTACHMENT15,
    COLOR_ATTACHMENT16 = GL_COLOR_ATTACHMENT16,
    COLOR_ATTACHMENT17 = GL_COLOR_ATTACHMENT17,
    COLOR_ATTACHMENT18 = GL_COLOR_ATTACHMENT18,
    COLOR_ATTACHMENT19 = GL_COLOR_ATTACHMENT19,
    COLOR_ATTACHMENT20 = GL_COLOR_ATTACHMENT20,
    COLOR_ATTACHMENT21 = GL_COLOR_ATTACHMENT21,
    COLOR_ATTACHMENT22 = GL_COLOR_ATTACHMENT22,
    COLOR_ATTACHMENT23 = GL_COLOR_ATTACHMENT23,
    COLOR_ATTACHMENT24 = GL_COLOR_ATTACHMENT24,
    COLOR_ATTACHMENT25 = GL_COLOR_ATTACHMENT25,
    COLOR_ATTACHMENT26 = GL_COLOR_ATTACHMENT26,
    COLOR_ATTACHMENT27 = GL_COLOR_ATTACHMENT27,
    COLOR_ATTACHMENT28 = GL_COLOR_ATTACHMENT28,
    COLOR_ATTACHMENT29 = GL_COLOR_ATTACHMENT29,
    COLOR_ATTACHMENT30 = GL_COLOR_ATTACHMENT30,
    COLOR_ATTACHMENT31 = GL_COLOR_ATTACHMENT31,
};

enum class ReadBufferMode
{
    NONE = GL_NONE,
    FRONT_LEFT = GL_FRONT_LEFT,
    FRONT_RIGHT = GL_FRONT_RIGHT,
    BACK_LEFT = GL_BACK_LEFT,
    BACK_RIGHT = GL_BACK_RIGHT,
    FRONT = GL_FRONT,
    BACK = GL_BACK,
    LEFT = GL_LEFT,
    RIGHT = GL_RIGHT,
    COLOR_ATTACHMENT0 = GL_COLOR_ATTACHMENT0,
    COLOR_ATTACHMENT1 = GL_COLOR_ATTACHMENT1,
    COLOR_ATTACHMENT2 = GL_COLOR_ATTACHMENT2,
    COLOR_ATTACHMENT3 = GL_COLOR_ATTACHMENT3,
    COLOR_ATTACHMENT4 = GL_COLOR_ATTACHMENT4,
    COLOR_ATTACHMENT5 = GL_COLOR_ATTACHMENT5,
    COLOR_ATTACHMENT6 = GL_COLOR_ATTACHMENT6,
    COLOR_ATTACHMENT7 = GL_COLOR_ATTACHMENT7,
    COLOR_ATTACHMENT8 = GL_COLOR_ATTACHMENT8,
    COLOR_ATTACHMENT9 = GL_COLOR_ATTACHMENT9,
    COLOR_ATTACHMENT10 = GL_COLOR_ATTACHMENT10,
    COLOR_ATTACHMENT11 = GL_COLOR_ATTACHMENT11,
    COLOR_ATTACHMENT12 = GL_COLOR_ATTACHMENT12,
    COLOR_ATTACHMENT13 = GL_COLOR_ATTACHMENT13,
    COLOR_ATTACHMENT14 = GL_COLOR_ATTACHMENT14,
    COLOR_ATTACHMENT15 = GL_COLOR_ATTACHMENT15,
    COLOR_ATTACHMENT16 = GL_COLOR_ATTACHMENT16,
    COLOR_ATTACHMENT17 = GL_COLOR_ATTACHMENT17,
    COLOR_ATTACHMENT18 = GL_COLOR_ATTACHMENT18,
    COLOR_ATTACHMENT19 = GL_COLOR_ATTACHMENT19,
    COLOR_ATTACHMENT20 = GL_COLOR_ATTACHMENT20,
    COLOR_ATTACHMENT21 = GL_COLOR_ATTACHMENT21,
    COLOR_ATTACHMENT22 = GL_COLOR_ATTACHMENT22,
    COLOR_ATTACHMENT23 = GL_COLOR_ATTACHMENT23,
    COLOR_ATTACHMENT24 = GL_COLOR_ATTACHMENT24,
    COLOR_ATTACHMENT25 = GL_COLOR_ATTACHMENT25,
    COLOR_ATTACHMENT26 = GL_COLOR_ATTACHMENT26,
    COLOR_ATTACHMENT27 = GL_COLOR_ATTACHMENT27,
    COLOR_ATTACHMENT28 = GL_COLOR_ATTACHMENT28,
    COLOR_ATTACHMENT29 = GL_COLOR_ATTACHMENT29,
    COLOR_ATTACHMENT30 = GL_COLOR_ATTACHMENT30,
    COLOR_ATTACHMENT31 = GL_COLOR_ATTACHMENT31,
};

class RenderTexture : public Texture
{
public: 
    GLuint m_framebufferID;
    std::vector<BufferAttachment> m_textureBuffers;
    std::vector<GLuint> m_backBuffer;

private:
    virtual void AttachTextureBuffer(BufferAttachment bufferAttachement, InternalFormat internalRenderableFormat, Format format, DataType dataTye, LayerTextureInfo layerTextureInfo = LayerTextureInfo());

public:
    RenderTexture(int width, int height);
    ~RenderTexture();

    int GetFrameBufferID()const;
    void BindFramebuffer();
    void UnBindFramebuffer();

    void AttachColorTextureBuffer(ColorRenderableFormat colorRenderableFormat, ColorFormat colorFormat, DataType dataTye, unsigned int colorAttachementIndex, LayerTextureInfo layerTextureInfo = LayerTextureInfo());
    void AttachDepthTextureBuffer(DepthRenderableFormat depthRenderableFormat, DataType dataTye, LayerTextureInfo layerTextureInfo = LayerTextureInfo());
    void AttachStencilTextureBuffer(StencilRenderableFormat stencilRenderableFormat, DataType dataTye, LayerTextureInfo layerTextureInfo = LayerTextureInfo());
    void AttachDepthStencilTextureBuffer(DepthStencilRenderableFormat depthStencilRenderableFormat, DataType dataTye, LayerTextureInfo layerTextureInfo = LayerTextureInfo());
    virtual void DetachBuffer(BufferAttachment bufferAttachment);

    virtual void Resize(int newWidth, int newHeight);
    virtual void SwapBuffer();
};

#endif

